module load openmpi 
module load cuda/11.1.1


#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#
#
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#
##grid
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#
#
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar10-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar100-cnn-alpha0.2 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100  --KD 0 --PS 0 --outputFolder Output


#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#
#
#
#
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-dsgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#
#
##pasgd
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#

mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar10-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output


#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar100-cnn-alpha0.05 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.05 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar10-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-pasgd-cifar100-cnn-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --outputFolder Output

#---------------------



#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test1-16C-dsgd-cifar10-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test2-16C-dsgd-cifar10-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test3-16C-dsgd-cifar10-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test4-16C-dsgd-cifar10-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test5-16C-dsgd-cifar10-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --KD 0 --PS 0 --outputFolder Output
#
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test1-16C-dsgd-cifar100-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test2-16C-dsgd-cifar100-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test3-16C-dsgd-cifar100-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test4-16C-dsgd-cifar100-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output
#mpirun -np 30 --oversubscribe python Train_pull_logit.py --graph clique-ring --rows 4 --columns 4 --num_clusters 6 --name pdsgd-noniid-test5-16C-dsgd-cifar100-cnn --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar100 --KD 0 --PS 0 --outputFolder Output



