module load openmpi 
module load cuda/11.1.1

mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-SDPS-cifar10-cnn-firstlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-SDPS-cifar10-cnn-firstlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-SDPS-cifar10-cnn-firstlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-SDPS-cifar10-cnn-firstlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1  --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-SDPS-cifar10-cnn-firstlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --layer first_cv --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_cv --outputFolder Output

mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-SDPS-cifar10-cnn-lastlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-SDPS-cifar10-cnn-lastlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-SDPS-cifar10-cnn-lastlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-SDPS-cifar10-cnn-lastlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_cv --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-SDPS-cifar10-cnn-lastlayer-conv --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_cv --outputFolder Output

mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-SDPS-cifar10-cnn-firstslayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-SDPS-cifar10-cnn-firstslayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-SDPS-cifar10-cnn-firstslayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-SDPS-cifar10-cnn-firstslayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-SDPS-cifar10-cnn-firstslayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer first_fc --outputFolder Output

mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test1-16C-SDPS-cifar10-cnn-lastlayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test2-16C-SDPS-cifar10-cnn-lastlayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 3789 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test3-16C-SDPS-cifar10-cnn-lastlayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 99 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test4-16C-SDPS-cifar10-cnn-lastlayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 122 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_fc --outputFolder Output
mpirun -np 16 --oversubscribe python Train_pull_logit_accuracy.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name pdsgd-noniid-test5-16C-SDPS-cifar10-cnn-lastlayer-fc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 2000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 37 --dataset cifar10 --lambda_kd 0.05 --KD 1 --layer last_fc --outputFolder Output