module load openmpi 
module load cuda/11.1.1

#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar10-pasgd-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output
#
mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar100-pasgd-alpha0.5-fortest --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output
##
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar10-sdps-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 1  --lambda_kd 0.1 --layer last_fc --outputFolder Output
##
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar100-sdps-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 1  --lambda_kd 0.1 --layer last_fc --outputFolder Output
###
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar10-sdpsrandom-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 1 --lambda_kd 0.05 --layer last_fc --outputFolder Output
##
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar100-sdpsrandom-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 1 --lambda_kd 0.05 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar10-dsgd-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 50 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar100-dsgd-alpha0.5 --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 50 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output

#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar10-sdps-noKD-alpha0.5-grid --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --layer last_fc --outputFolder Output
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph grid --rows 4 --columns 4 --num_clusters 4 --name cifar100-sdps-noKD-alpha0.5-grid --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --layer last_fc --outputFolder Output



#roc

#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar10-pasgd-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar100-pasgd-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar10-sdps-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 1  --lambda_kd 0.1 --layer last_fc --outputFolder Output
##
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar100-sdps-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 1  --lambda_kd 0.1 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar10-sdpsrandom-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 1 --lambda_kd 0.05 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar100-sdpsrandom-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 1 --lambda_kd 0.05 --layer last_fc --outputFolder Output

#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar10-dsgd-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar100-dsgd-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 8000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --PS 0 --layer last_fc --outputFolder Output

#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar10-sdps-noKD-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --layer last_fc --outputFolder Output
#
#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar100-sdps-noKD-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 4 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection bnz --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar100 --alpha 0.5 --KD 0 --layer last_fc --outputFolder Output

#mpirun -np 16 --oversubscribe python Train_pull_logit_time.py --graph clique-ring --rows 4 --columns 4 --num_clusters 4 --name cifar10-pasgdrandom-noKD-alpha0.5-roc --comm_style pd-sgd-selection --momentum 0.9 --i1 0 --i2 1 --lr 0.01 --customLR 1 --degree_noniid 0.9 --noniid 1 --resSize 18 --bs 32 --epoch 4000 --selection random --utility_metric cosine_similarity_weight --description PDSGD --randomSeed 2828 --dataset cifar10 --alpha 0.5 --KD 0 --layer last_fc --outputFolder Output

